version: '3.8'

services:
  bff-biblioteca:
    build:
      context: ./bff-biblioteca
      dockerfile: Dockerfile
    container_name: bff-biblioteca
    ports:
      - "8080:8080"
    environment:
      - FAAS_USUARIOS_URL=https://fn-usuarios-biblioteca-dkbag6cefwcpfube.brazilsouth-01.azurewebsites.net/api
      - FAAS_PRESTAMOS_URL=https://fn-prestamos-biblioteca-fefqfdc7bdewcvbc.brazilsouth-01.azurewebsites.net/api
