server.port=8080
spring.application.name=bff-biblioteca

# URLs de las Azure Functions
faas.usuarios.url=${FAAS_USUARIOS_URL:https://fn-usuarios-biblioteca-dkbag6cefwcpfube.brazilsouth-01.azurewebsites.net/api}
faas.prestamos.url=${FAAS_PRESTAMOS_URL:https://fn-prestamos-biblioteca-fefqfdc7bdewcvbc.brazilsouth-01.azurewebsites.net/api}
